vich_uploader:
    db_driver: orm
        # types:
        #     image: 'Vich\UploaderBundle\Storage\FlysystemStorage'

    mappings:
      produit_image:
       # chemin public pour accéder aux images
           uri_prefix: /IMG
        # hemin de destination où les fichiers seront stockés
           upload_destination: '%kernel.project_dir%/public/IMG'
        # type de nommage que je souhaites utiliser pour les fichiers uploadés
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      categorie_image:
            uri_prefix: /IMG
            upload_destination: '%kernel.project_dir%/public/IMG'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        # categorie_image:
        #     uri_prefix: /uploads/images/categories
        #     upload_destination: '%kernel.project_dir%/public/uploads/images/categories'
            # facultatif pour générer des noms de fichier aléatoires
            # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            # delete_on_remove: true
            # delete_on_update: true
